sudo: false
language: minimal
git:
  submodules: false  # whether to recursively clone submodules

cache:
  directories:
    - $HOME/.stack

matrix:
  include:
  - env: STACK_YAML=stack-8.4.yaml
  - env: STACK_YAML=stack-8.6.yaml


before_install:
# Changes ssh paths into http path, so that we can do a read-only clone of
# our submodules without worrying about ssh keys.
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init

# Download and unpack the stack executable
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
 - travis_wait stack --no-terminal setup

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 - stack build macaw-x86 macaw-x86-symbolic
 - stack test macaw-x86
